# Generated by Django 4.0 on 2022-03-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upload_pics',
            field=models.ImageField(default='default.jpg', upload_to='article_pics'),
        ),
    ]
