# Generated by Django 4.0.2 on 2022-03-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, unique_for_date='published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
