# Generated by Django 4.0.2 on 2022-03-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_api', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active',
        ),
    ]
