# Generated by Django 4.0 on 2022-03-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_api', '0006_authorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article_api.post'),
        ),
    ]
