# Generated by Django 4.0 on 2022-03-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('article_api', '0008_alter_authorprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
